config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  devise_for :accounts

  resources :welcome, only: %i[ index ]
  get 'deposito', to: 'welcome#deposito'
  get 'saque', to: 'welcome#saque'
  get 'transferencia', to: 'welcome#transferencia'
  get 'extrato', to: 'welcome#extrato'

  resources :orders, only: %i[ create ]
  post 'deposito', to: 'orders#create'
  post 'saque', to: 'orders#create'
  post 'transferencia', to: 'orders#create'

end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :bank
  has_many :orders

  enum status: %i[ ativo inativo ]

  validates_presence_of :name
  validates_presence_of :document
  validates_presence_of :agency

  before_validation :generate_bank_account

  def balance
    self.value
  end

  protected
  # Gerenado uma conta bancária para o usuário
  def generate_bank_account
    if self.bank_id.nil? || self.bank_id.blank?
      begin
        banco = Bank.all.sample
        self.bank_id = banco.id != nil ? banco.id : 1
        self.agency = rand(100..999).to_s
        self.num_account = rand(1000..9999)
      end while Account.exists?(agency) && Account.exists?(num_account)
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank.rb
class Bank < ApplicationRecord

  enum status: %i[ ativo inativo ]
  validates :name, presence: true
  validates :cod_bank, presence: true

  has_many :accounts

  def full_bank_name
    "#{cod_bank}-#{name}"
  end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :account
  belongs_to :favored, optional: true, foreign_key: :favored_by, class_name: 'Account'

  validates :type_order, presence: true
  validates :value, presence: true
  validates :fee, presence: true

  enum status: %i[ ativo inativo ]
  enum type_order: %i[ deposito saque transferencia ]

  scope :bank_statement, ->(account_holder) { where("created_at <= ? AND created_at >= ?", DateTime.now, DateTime.now - 10)
                                                                    .where("account_id = ? OR favored_id = ?", account_holder, account_holder)}

  after_create :balance_transation

  def quality_amount(conta)
    if self.type_order != 'deposito' && self.account.id == conta.id
      "- #{self.value}"
    else
      "#{self.value}"
    end
  end

  def favored_name(conta)
  if conta.id != self.favored_id
    Account.find_by_id(self.favored_id).name
  else
    account.name
  end
end

  def saida_amount?(conta)
    self.type_order != 'deposito' && self.account.id == conta.id
  end

  def setting_fee
    ted_amount - self.value
  end

  def balance_ted?
    account.balance >= ted_amount
  end


  def saque_permited?
    account.balance >= self.value
  end

  private

  def balance_transation
    if self.type_order == 'transferencia'
      confirm_ted
    elsif self.type_order == 'saque'
      account.update(value: account.value -= self.value)
    else
      account.update(value: account.value += self.value)
    end
  end

  def confirm_ted
    saldo = account.balance - ted_amount
    cliente = Account.find_by_id(self.favored_id)
    account.update(value: saldo)
    cliente.update(value: cliente.value += self.value)
  end

  def ted_amount
    amount = '5.0'.to_d
    amount = '7.0'.to_d if set_fee?
    amount += '10.0'.to_d if ted_limit_without_fee?
    amount += self.value
  end

  def weekend?
    Time.now.wday == 0 || Time.now.wday == 6
  end

  def hour_comercial?
    Time.now.hour < 8 || Time.now.hour > 18
  end

  def set_fee?
    weekend? || hour_comercial?
  end

  def ted_limit_without_fee?
    self.value > '999.9'.to_d
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_account!
  before_action :configure_permited_parameters, if: :devise_controller?

  layout :layout_by_resource

  private

  def layout_by_resource
    "authentication" if devise_controller?
  end

  def configure_permited_parameters
    devise_parameter_sanitizer.permit :sign_up, keys: %i[ name document agency num_account bank_id]
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def create
    @order = current_account.orders.new(order_params)

    if @order.type_order == 'deposito'
      if @order.save
        redirect_to root_path, notice: 'Depósito efetuado com sucesso!!!'
      else
        redirect_to deposito_path, alert: @order.errors.full_messages
      end

    elsif @order.type_order == 'saque'
      if @order.saque_permited?
        if @order.save
          redirect_to root_path, notice: 'Saque efetuado com sucesso!!!'
        else
          redirect_to deposito_path, alert: @order.errors.full_messages
        end
      else
        redirect_to saque_path, alert: 'Saldo insuficiente!'
      end

    elsif @order.type_order == 'transferencia'
      if @order.balance_ted?
        @order.fee = @order.setting_fee
        if @order.save
          redirect_to root_path, notice: 'Ted efetuado com sucesso!!!'
        else
          redirect_to deposito_path, alert: @order.errors.full_messages
        end
      else
        redirect_to transferencia_path, alert: 'Saldo Insuficiente!!!'
      end

    end

  end

  private

  def order_params
    params.require(:order).permit(:type_order, :value, :fee, :status, :favored_id)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @extratos = Order.bank_statement(current_account)
  end

  def deposito
    @order = Order.new
  end

  def saque
    @order = Order.new
  end

  def transferencia
    @order = Order.new
  end

  def extrato
  look = params['date_start'].nil?

  if look
    @inicio = Date.today - 5
    @fim = Date.today + 1
  elsif params['date_start'] == '' || params['date_end'] == ''
    @inicio = Date.today - 5
    @fim = Date.today + 1
  elsif params['date_start'] > params['date_end']
    @inicio = Date.today - 5
    @fim = Date.today + 1
  else
    @inicio = params['date_start'].to_datetime
    @fim = change_date(params['date_end']).to_datetime
  end
end

private

def change_date(data)
  dt = data.split('-')
  set_data = Date.new(dt[0].to_i,dt[1].to_i,dt[2].to_i + 1)
end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def list_favored(current)
    Account.all.map { |account| [account.name, account.id] if account != current }
  end

  def extrato(conta, date_start = DateTime.now - 5, date_end = DateTime.now)
    Order.where("account_id = ? OR favored_id = ?", conta.id, conta.id)
                      .where("created_at >= ? AND created_at <= ?", date_start, date_end)
  end

end

app/views/layouts/application.html.haml
// Arquivo padrão de configuração - W3n designer
!!! 5
%html
  %head
    %title bank-nobe
    = csrf_meta_tags
    = csp_meta_tag
    = favicon_link_tag asset_path('favicon.png')
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0" }

    = stylesheet_pack_tag 'application'
    = javascript_pack_tag 'application'

  %body{:data => {:flash => {:messages => "#{JSON.dump(flash.to_a)}"}}}
    = render 'shared/menubar'

    .container.mt-2
      #wrapper_conteudo
        #menu_wrapper
          = render 'shared/sidebar'

        #conteudo_wrapper
          #cabecalho
            .titular
              %h2 #{ current_account.name }
            .dados_bancarios
              .banco
                %small Banco:
                %b #{ current_account.bank.full_bank_name }
              .agency
                %small Agência:
                %b #{ current_account.agency }
              .account
                %small Conta:
                %b #{ current_account.num_account }
          = yield
          #footer_account.pr-5
            %small Saldo
            %span.saldo #{ number_to_currency current_account.value }

app/views/layouts/authentication.html.haml
// Arquivo padrão de configuração - W3n designer
!!! 5
%html
  %head
    %title adm::bank-nobe
    = csrf_meta_tags
    = csp_meta_tag
    = favicon_link_tag asset_path('favicon.png')
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0" }

    = stylesheet_pack_tag 'authentication'
    = javascript_pack_tag 'authentication'

  %body{:data => {:flash => {:messages => "#{JSON.dump(flash.to_a)}"}}}
    = yield

app/views/orders/_extrato.html.haml
%table.table.is-fullwidth
  %thead
    %tr
      %th{ width: '16%' } Data
      %th{ width: '24%' } Transação
      %th{ width: '42%'} Favorecido(a) / Origem
      %th{ width: '8%'} Taxa
      %th{width: '10%'} Valor
  %tbody
    - if extrato(current_account) != nil
      - extrato(current_account).each do |order|
        %tr{ style: ("background-color: #fdefec" unless !order.saida_amount?(current_account)) }
          %td #{ order.created_at.strftime("%d/%m/%Y") }
          %td #{ order.type_order }
          %td
            - unless order.favored_id.blank?
              #{ order.favored_name(current_account) }
          %td
            - if order.fee > 0
              = '- '
              #{ number_to_currency order.fee }
          %td
            #{ number_to_currency order.quality_amount(current_account) }

app/views/orders/_extrato_periodo.html.haml
%table.table.is-fullwidth
  %thead
    %tr
      %th{ width: '16%' } Data
      %th{ width: '24%' } Transação
      %th{ width: '42%'} Favorecido(a) / Origem
      %th{ width: '8%'} Taxa
      %th{width: '10%'} Valor
  %tbody
    - if extrato(current_account, @inicio, @fim) != nil
      - extrato(current_account, @inicio,@fim).each do |order|
        %tr{ style: ("background-color: #fdefec" unless !order.saida_amount?(current_account)) }
          %td #{ order.created_at.strftime("%d/%m/%Y") }
          %td #{ order.type_order }
          %td
            - unless order.favored_id.blank?
              #{ order.favored_name(current_account) }
          %td
            - if order.fee > 0
              = '- '
              #{ number_to_currency order.fee }
          %td
            #{ number_to_currency order.quality_amount(current_account) }

app/views/orders/_form.html.haml
= form_with(model: @order, local: true) do |form|
  = form.hidden_field :type_order, value: tipo
  .field
  = form.label 'Valor', class: 'label'
  .columns
    .column
      .field
        .control
          = form.number_field :value, class: 'input', step: :any, maxlength: 7, wrapper: false
          %span
            %small ex: 500.00 / 1000.00
    .column
      .field
        = form.submit 'Enviar', class: 'button is-info'

app/views/orders/_form_transferencia.html.haml
= form_with(model: @order, local: true) do |form|
  = form.hidden_field :type_order, value: tipo
  .field
    = form.label 'Valor', class: 'label'
    .control
      = form.number_field :value, class: 'input', step: :any
      %span
        %small ex.: 500.00 / 1000.00
  .field
    = form.label 'Favorecido', class: 'label'
    .control
      %span.select
        = form.select :favored_id, list_favored(current_account)
  .field
    = form.submit 'Enviar', class: 'button is-info'

app/views/orders/index.html.haml
%h1 Orders

app/views/shared/_menubar.html.haml
%nav.navbar.has-background-white
  .container
    .navbar-brand
      = link_to root_path, class: 'navbar-item' do
        %h2.subtitle nobe-Bank
    .navbar-menu
      .navbar-end
        - if account_signed_in?
          .navbar-item
            = link_to destroy_account_session_path, method: :delete, data: { confirm: 'Centerza que deseja sair?' }, class: 'button is-danger' do
              Sair
        -else
          .navbar-item
            = link_to new_account_session_path, class: 'button is-info' do
              Entrar
          .navbar-item
            = link_to new_account_registration_path, class: 'button is-warning' do
              Cadastrar-se

app/views/shared/_sidebar.html.haml
%sidebar
  .sidebar_menu
    = link_to root_path, class: 'link_menu' do
      .link_content
        %span.link_icon
          %i.fas.fa-home
        %span.link_text
          Home

    = link_to deposito_path, class: 'link_menu' do
      .link_content
        %span.link_icon
          %i.fas.fa-piggy-bank
        %span.link_text
          Depósito

    - if current_account.value > 0
      = link_to saque_path, class: 'link_menu' do
        .link_content
          %span.link_icon
            %i.fas.fa-wallet
          %span.link_text
          Saque
      = link_to transferencia_path, class: 'link_menu' do
        .link_content
          %span.link_icon
            %i.fas.fa-money-bill-wave
          %span.link_text
            Transferência

      = link_to extrato_path, class: 'link_menu' do
        .link_content
          %span.link_icon
            %i.fas.fa-coins
          %span.link_text
            Extrato

app/views/welcome/deposito.html.haml
.display_content
  .conteudo_central
    %h1.title Depósito
    = render 'orders/form', tipo: :deposito

app/views/welcome/extrato.html.haml
#transacoes
  %h2.title.is-6
    Extrato
  .form_extrato_periodo.mt-0.mb-4
    = form_with(url: extrato_path, local: true, method: :get) do |f|
      .columns
        .column
          %small Início
          .field
            .control
              = f.date_field :date_start, value: @inicio.to_date
        .column
          %small final
          .field
            .control
              = f.date_field :date_end, value: (@fim - 1).to_date
        .column
          .field
            = f.submit 'Consultar', class: 'button is-small is-dark'
  #extrato_table
    = render 'orders/extrato_periodo', conta: current_account

app/views/welcome/index.html.haml
#transacoes
  %h2.title.is-6
    Extrato dos últimos 10 dias
  #extrato_table
    = render 'orders/extrato', conta: current_account

app/views/welcome/saque.html.haml
.display_content
  .conteudo_central
    %h1.title Saque
    = render 'orders/form', tipo: :saque

app/views/welcome/transferencia.html.haml
.display_content
  .conteudo_central
    %h1.title Transferência
    = render 'orders/form_transferencia', tipo: :transferencia